# -*- coding: utf-8 -*-
"""GA_RF_With_Feature_Selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hF_htoLmX5ZX1W1Ya-XctFH4naX0mH_T
"""

from google.colab import drive
drive.mount("/content/gdrive")

!pip install tpot

"""#Import Library"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss

import numpy as np
import pandas as pd
import random
import sklearn 
import seaborn as sns
from sklearn import model_selection
import matplotlib.pyplot as plt
from mlxtend.preprocessing import minmax_scaling

from sklearn.svm import SVC
import random
from sklearn.preprocessing import LabelEncoder
import sklearn.metrics as metrics
import pandas as pd
from sklearn import preprocessing

from sklearn.ensemble import RandomForestClassifier
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import math
import sklearn.metrics as metrics
from sklearn import preprocessing
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

#df = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/GA with feature selection/heart.csv",encoding = "ISO-8859-1")
df = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/practise data_set/Updated_Turk.csv",encoding = "ISO-8859-1")
ndf = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/practise data_set/Updated_Turk.csv",encoding = "ISO-8859-1")

"""#Class Balancing"""

#df=df.apply(lbl.fit_transform)
#ndf=ndf.apply(lbl.fit_transform)
target_count = df.Rating.value_counts()
target_count[3]
target_count.plot(kind='bar', title='Count (target)')
df_class_1 = df[df['Rating'] == 1]
df_class_2 = df[df['Rating'] == 2]
df_class_4 = df[df['Rating'] == 4]
df_class_3 = df[df['Rating'] == 3]
df_class_1_under = df_class_1.sample(target_count[3],replace=True)
df_class_2_under = df_class_2.sample(target_count[3],replace=True)
df_class_4_under = df_class_4.sample(target_count[3],replace=True)
df = pd.concat([df_class_1_under,df_class_2_under,df_class_3,df_class_4_under], axis=0)
ndf = df
target_count = df.Rating.value_counts()
target_count[3]
target_count.plot(kind='bar',figsize=(10, 6),title='Count (target)',color='purple')
print("DF ISNULL: ",df.isnull().sum())

df.isnull()

"""#BOX-Ploting & Data prepossing"""

df.dtypes
#df = df.drop('y', axis=1)
#ndf = ndf.drop('y', axis=1)
df = df.sort_values(by=['Rating'], inplace=False)
#print(df)
df.columns
df = df.reset_index(drop=True)
#print(df)

ndf = ndf.sort_values(by=['Rating'], inplace=False)
#print(df)

ndf = ndf.reset_index(drop=True)
#print(df)
df.describe()


df = df.apply(pd.to_numeric,errors='coerce')
df.columns
df = df.astype('float32')
#df = df.astype('float64')
df.describe()
df.dtypes




ind=df.index.to_series().groupby(df['Rating']).agg(['first','last']).reset_index()
ind
f=0
p=0
df.dtypes
df.describe()
#detecting and replacing outliers by mean
for m in range(1,4):
 A = df.loc[df['Rating'] == m]
 #print(A.shape)
 first=ind.iloc[p,1]
 #print(first)
 last=ind.iloc[p,2]
 #print(last)
 for i in range(0,27):
  #print("For i=i.value")
  Avg= np.mean(A.iloc[:,i])
  #print(Avg)
  Q1 = A.iloc[:,i].quantile(0.25)
  #print(Q1)
  Q3 = A.iloc[:,i].quantile(0.75)
  #print(Q3)
  IQR = Q3 - Q1
  lim1=(Q1 - 1.5 * IQR)
  #print(lim1)
  lim2=(Q3 + 1.5 * IQR)
  #print(lim2)
  #print(IQR)
  for ami in range(first,last+1):
      com=df.iloc[ami,i]
      if ((com < lim1) |(com > lim2)):
          #print(newdf.iloc[ami,i])
          df.iloc[ami,i] = Avg
          #print(Avg)
          #print(newdf.iloc[ami,i])
          f=f+1
  #C= A.replace(((A.iloc[ami,i] < (Q1 - 1.5 * IQR)) |(A.iloc[:,i] > (Q3 + 1.5 * IQR))), Avg)
  #print(f)
 if(p<4):
     p=p+1
     
#data without outliers boxplot
df.describe()

count=0
ndf.iloc[31:212,:1].max()


df.columns

"""#GA for feature selection START

"""

target=df.Rating

df=df.fillna(1)

target, feature_list = "Rating", [i for i in df.columns if i not in target]

# Print list of features and target variable names
print('Feature List\n',feature_list, '\n\nTarget = ',target)

def init_population(n,c):
    return np.array([[math.ceil(e) for e in pop] for pop in (np.random.rand(n,c)-0.5)]), np.zeros((2,c))-1

def single_point_crossover(population):
    r,c, n = population.shape[0], population.shape[1], np.random.randint(1,population.shape[1])         
    for i in range(0,r,2):                
        population[i], population[i+1] = np.append(population[i][0:n],population[i+1][n:c]),np.append(population[i+1][0:n],population[i][n:c])        
    return population

def flip_mutation(population):
    return population.max() - population

def random_selection(population):
    r = population.shape[0]
    new_population = population.copy()    
    for i in range(r):        
        new_population[i] = population[np.random.randint(0,r)]
    return new_population

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""#Feature selection"""

def get_fitness(data, feature_list, target, population):    
    fitness = []
    for i in range(population.shape[0]):        
        columns = [feature_list[j] for j in range(population.shape[1]) if population[i,j]==1]                    
        fitness.append(predictive_model(data[columns], data[target]))                
    return fitness

def predictive_model(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=7)
    lr = LogisticRegression(solver='liblinear', max_iter=100, random_state=7)
    lr.fit(X_train,y_train)    
    return accuracy_score(y_test, lr.predict(X_test))

"""#MAIN"""

def ga(data, feature_list, target, n, max_iter):
    
    c = len(feature_list)
    
    population, memory = init_population(n,c)
    #population, memory = replace_duplicate(population, memory)    
    
    fitness= get_fitness(data, feature_list, target, population)    
    
    optimal_value    = max(fitness)
    optimal_solution = population[np.where(fitness==optimal_value)][0]    
    
    for i in range(max_iter):                
        population = random_selection(population)
        population = single_point_crossover(population)                        
        if np.random.rand() < 0.3:
            population = flip_mutation(population)   
        
        #population, memory = replace_duplicate(population, memory)
                
        fitness = get_fitness(data, feature_list, target, population)
                
        if max(fitness) > optimal_value:
            optimal_value    = max(fitness)
            optimal_solution = population[np.where(fitness==optimal_value)][0]                               
        
    return optimal_solution, optimal_value

# Execute Genetic Algorithm to obtain Important Feature
#feature_set, acc_score = ga(df, feature_list, target, 10, 1000)
relevant_features, acc_score = ga(df, feature_list, target, 10, 10)


# Filter Selected Features
relevant_features = [feature_list[i] for i in range(len(feature_list)) if relevant_features[i]==1]

# Print List of Features
print('Optimal Feature Set\n',relevant_features,'\nOptimal Accuracy =', round(acc_score*100), '%')
tol = len(relevant_features)
print("\nTotal number:",tol)

df = df.iloc[:,[1,2,3,7,8,9,10,13,14,16,17,22,23,24,25,26,28]]

"""#Find Feature Index"""

print(feature_list.index( 'Liquid Assets / (Deposits + Non-Deposit Funds)'))

df.describe()

df.dtypes
y = df['Rating'].values

df = df.drop('Rating', axis=1)
df.describe()
df.dtypes
cnames = list(df.columns)
cnames
df.describe()
df.dtypes
df.isnull().sum()
df.dtypes
df = df.fillna(df.mean(), inplace=False)
df.dtypes
df.isnull().sum()
df.dtypes
df = df.astype('float32')
df.dtypes
df.describe()


X = minmax_scaling(df,columns = cnames,min_val=0,max_val=1)

cnam = len(cnames)
print("total:",cnam)

"""#GA using parameter optimization & Final Classification"""

Trainaccuracy = []

Testaccuracy = []

SVMC = []

SVMG = []
n = 5

for i in range(n):
    print("\n\nCross Validation: " ,i+1)
    X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.30)
    tpot_config = {
        'sklearn.ensemble.RandomForestClassifier': {
        'n_estimators': range(1, 100),
        'criterion': ["gini", "entropy"],
        'max_depth': range(1, 100)
    }}

    tpot = TPOTClassifier(generations=10, population_size=10, verbosity=2,config_dict=tpot_config)
    #tpot=TPOTClassifier(generations=5, population_size=20,offspring_size=None, mutation_rate=0.9,crossover_rate=0.1,scoring='accuracy', cv=5,subsample=1.0, n_jobs=1,max_time_mins=None, max_eval_time_mins=5,random_state=None, config_dict=tpot_config,template=None,warm_start=False,memory=None,use_dask=False,periodic_checkpoint_folder=None,early_stop=None,verbosity=0,disable_update_check=False,log_file=None)   

    research=tpot.fit(X_train, y_train)
    M=research.fitted_pipeline_
    print("M=",M)
    pipe = Pipeline([('scaler', StandardScaler()), ('RandomForestClassifier', RandomForestClassifier())])
    
    pipe.fit(X_train, y_train)
    Pipeline(steps=[('scaler', StandardScaler()), ('RandomForestClassifier', RandomForestClassifier())])
    pipe.score(X_test, y_test)

    P = pipe.predict(X_train)
    trainacc = float((y_train== P).sum()) / P.shape[0]
    #print('Train set accuracy: %.2f %%' % (acc*100))
 
    
    Trainaccuracy.append(trainacc)
    P = pipe.predict(X_test)
    testacc = float((y_test== P).sum()) / P.shape[0]
    #print('Test set accuracy: %.2f %%' % (acc*100))
    Testaccuracy.append(testacc)
print("\n\n")
for i in range(5): 
    print( Trainaccuracy[i]*100,"%", Testaccuracy[i]*100,"%" )
print("\n\n")
print(sum(Testaccuracy)/len(Testaccuracy))
print(sum(Trainaccuracy)/len(Trainaccuracy))



Trainaccuracy

for i in range(5): 
    print( Trainaccuracy[i]*100,"%", Testaccuracy[i]*100,"%" )