# -*- coding: utf-8 -*-
"""GA_SVM_Without_Feature_Selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HUJp0Fv7BXzvKO3awhG2ofqBzvDwWZX7
"""

from google.colab import drive
drive.mount("/content/gdrive")

!pip install -U scikit-learn

!pip install tpot

"""#Import Library"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss

import numpy as np
import pandas as pd
import random
import sklearn 
import seaborn as sns
from sklearn import model_selection
import matplotlib.pyplot as plt
from mlxtend.preprocessing import minmax_scaling
#from sklearn.datasets import load_iris
from sklearn.svm import SVC
import random
from sklearn.preprocessing import LabelEncoder
import sklearn.metrics as metrics
import pandas as pd
from sklearn import preprocessing

from sklearn.ensemble import RandomForestClassifier
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

"""#Dataset upload"""

lbl = LabelEncoder()
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
i=0
#from sklearn.datasets import make_classification
#X, y = make_classification(n_samples=100, n_features=15, n_classes=3,
                           #n_informative=4, n_redundant=1, n_repeated=2,
                           #random_state=1)


df = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/practise data_set/Updated_Turk.csv",encoding = "ISO-8859-1")
ndf = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/practise data_set/Updated_Turk.csv",encoding = "ISO-8859-1")

df

"""#Class Balancing"""

target_count = df.Rating.value_counts()

target_count[3]
target_count.plot(kind='bar', title='Count (target)')
df_class_1 = df[df['Rating'] == 1]
df_class_2 = df[df['Rating'] == 2]
df_class_4 = df[df['Rating'] == 4]
df_class_3 = df[df['Rating'] == 3]
df_class_1_under = df_class_1.sample(target_count[3],replace=True)
df_class_2_under = df_class_2.sample(target_count[3],replace=True)
df_class_4_under = df_class_4.sample(target_count[3],replace=True)
df = pd.concat([df_class_1_under,df_class_2_under,df_class_3,df_class_4_under], axis=0)
ndf = df
target_count = df.Rating.value_counts()
target_count[3]
#plt.bar(df_class_1_under, df_class_2_under, df_class_4_under, color=['red', 'blue', 'purple'])
target_count.plot(kind='bar',figsize=(10, 6),title='Count (target)',color='purple')
#plt.bar(df_class_1_under,height="5",  color='green')
print("DF ISNULL: ",df.isnull().sum())

"""#Box ploting & Data preprocessing"""

df.dtypes
#df = df.drop('y', axis=1)
#ndf = ndf.drop('y', axis=1)
df = df.sort_values(by=['Rating'], inplace=False)
#print(df)
df.columns
df = df.reset_index(drop=True)
#print(df)

ndf = ndf.sort_values(by=['Rating'], inplace=False)
#print(df)

ndf = ndf.reset_index(drop=True)
#print(df)
df.describe()


df = df.apply(pd.to_numeric,errors='coerce')
df.columns
df = df.astype('float32')
df.describe()
df.dtypes




ind=df.index.to_series().groupby(df['Rating']).agg(['first','last']).reset_index()
ind
f=0
p=0
df.dtypes
df.describe()
#detecting and replacing outliers by mean
for m in range(1,4):
 A = df.loc[df['Rating'] == m]
 #print(A.shape)
 first=ind.iloc[p,1]
 #print(first)
 last=ind.iloc[p,2]
 #print(last)
 for i in range(0,27):
  #print("For i=i.value")
  Avg= np.mean(A.iloc[:,i])
  #print(Avg)
  Q1 = A.iloc[:,i].quantile(0.25)
  #print(Q1)
  Q3 = A.iloc[:,i].quantile(0.75)
  #print(Q3)
  IQR = Q3 - Q1
  lim1=(Q1 - 1.5 * IQR)
  #print(lim1)
  lim2=(Q3 + 1.5 * IQR)
  #print(lim2)
  #print(IQR)
  for ami in range(first,last+1):
      com=df.iloc[ami,i]
      if ((com < lim1) |(com > lim2)):
          #print(newdf.iloc[ami,i])
          df.iloc[ami,i] = Avg
          #print(Avg)
          #print(newdf.iloc[ami,i])
          f=f+1
  #C= A.replace(((A.iloc[ami,i] < (Q1 - 1.5 * IQR)) |(A.iloc[:,i] > (Q3 + 1.5 * IQR))), Avg)
  #print(f)
 if(p<4):
     p=p+1
     
#data without outliers boxplot
df.describe()

count=0
ndf.iloc[31:212,:1].max()


df.columns
#df = df.drop('id', axis=1)
#ndf = ndf.drop('id', axis=1)


df.dtypes
y = df['Rating'].values

df = df.drop('Rating', axis=1)
df.describe()
df.dtypes
cnames = list(df.columns)
cnames
df.describe()
df.dtypes
df.isnull().sum()
df.dtypes
df = df.fillna(df.mean(), inplace=False)
df.dtypes
df.isnull().sum()
df.dtypes
df = df.astype('float32')
df.dtypes
df.describe()


X = minmax_scaling(df,columns = cnames,min_val=0,max_val=1)

from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

from tpot import TPOTClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

"""# Final Classification"""

Trainaccuracy = []

Testaccuracy = []

n = 5

for i in range(n):
    print("\n\nCross Validation: " ,i+1)
    X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.30)
    
    from scipy.stats import uniform as sp_rand
    #param_grid = {'C': sp_rand(1,100),'gamma': sp_rand(1,100)}
    classifier = SVC(kernel='rbf')
    gs=[random.uniform(1,100) for _ in range(100)]
    cs=[random.uniform(1,100) for _ in range(100)]
   
    
    #rsearch=TPOTClassifier(generations=100, population_size=100,offspring_size=None, mutation_rate=0.9,crossover_rate=0.1,scoring='accuracy', cv=5,subsample=1.0, n_jobs=1,max_time_mins=None, max_eval_time_mins=5,random_state=None, config_dict=None,template=None,warm_start=False,memory=None,use_dask=False,periodic_checkpoint_folder=None,early_stop=None,verbosity=0,disable_update_check=False,log_file=None)   
    #rsearch=TPOTClassifier(generations=10, population_size=100,offspring_size=None, mutation_rate=0.9,crossover_rate=0.1,scoring='accuracy', cv=5,subsample=1.0, n_jobs=1,max_time_mins=None, max_eval_time_mins=5,random_state=None, config_dict='TPOT light',template=None,warm_start=False,memory=None,use_dask=False,periodic_checkpoint_folder=None,early_stop=None,verbosity=0,disable_update_check=False,log_file=None)   

    tpot_config = {
    'sklearn.svm.SVC': {
        
        'gamma': gs,
        'C': cs
    }}

    tpot = TPOTClassifier(generations=10, population_size=10, mutation_rate=0.9,crossover_rate=0.1,verbosity=2,config_dict=tpot_config)
    #tpot=TPOTClassifier(generations=5, population_size=20,offspring_size=None, mutation_rate=0.9,crossover_rate=0.1,scoring='accuracy', cv=5,subsample=1.0, n_jobs=1,max_time_mins=None, max_eval_time_mins=5,random_state=None, config_dict=tpot_config,template=None,warm_start=False,memory=None,use_dask=False,periodic_checkpoint_folder=None,early_stop=None,verbosity=0,disable_update_check=False,log_file=None)   

    research=tpot.fit(X_train, y_train)
    M=research.fitted_pipeline_
    print("M=",M)
    pipe = Pipeline([('scaler', StandardScaler()), ('svc', SVC())])
     # The pipeline can be used as any other estimator
      # and avoids leaking the test set into the train set
    pipe.fit(X_train, y_train)
    Pipeline(steps=[('scaler', StandardScaler()), ('svc', SVC())])
    pipe.score(X_test, y_test)

    P = pipe.predict(X_train)
    trainacc = float((y_train== P).sum()) / P.shape[0]
    #print('Train set accuracy: %.2f %%' % (acc*100))
 
    
    Trainaccuracy.append(trainacc)
    P = pipe.predict(X_test)
    testacc = float((y_test== P).sum()) / P.shape[0]
    #print('Test set accuracy: %.2f %%' % (acc*100))
    Testaccuracy.append(testacc)
print("\n\n")
for i in range(5): 
    print( Trainaccuracy[i]*100,"%", Testaccuracy[i]*100,"%" )
print("\n\n")
print(sum(Testaccuracy)/len(Testaccuracy))
print(sum(Trainaccuracy)/len(Trainaccuracy))