# -*- coding: utf-8 -*-
"""RandomSearch_RF_With_Feature_Selection_Correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLuhmKW-YPd1Ze3f34VzDKy-DqXlaOm_
"""

from google.colab import drive
drive.mount("/content/gdrive")

!pip install tpot

!pip install -U scikit-learn

"""#Import Library"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss

import numpy as np
import pandas as pd
import random
import sklearn 
import seaborn as sns
from sklearn import model_selection
import matplotlib.pyplot as plt
from mlxtend.preprocessing import minmax_scaling
#from sklearn.datasets import load_iris
from sklearn.svm import SVC
import random
from sklearn.preprocessing import LabelEncoder
import sklearn.metrics as metrics
import pandas as pd
from sklearn import preprocessing

from sklearn.ensemble import RandomForestClassifier
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

"""#Import Dataset"""

lbl = LabelEncoder()
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
i=0
#from sklearn.datasets import make_classification
#X, y = make_classification(n_samples=100, n_features=15, n_classes=3,
                           #n_informative=4, n_redundant=1, n_repeated=2,
                           #random_state=1)


df = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/practise data_set/Updated_Turk.csv",encoding = "ISO-8859-1")
ndf = pd.read_csv("/content/gdrive/My Drive/My Thesis work/MY work/GA/practise data_set/Updated_Turk.csv",encoding = "ISO-8859-1")

df

"""#Class Balancing"""

target_count = df.Rating.value_counts()
target_count[3]
target_count.plot(kind='bar', title='Count (target)')
df_class_1 = df[df['Rating'] == 1]
df_class_2 = df[df['Rating'] == 2]
df_class_4 = df[df['Rating'] == 4]
df_class_3 = df[df['Rating'] == 3]
df_class_1_under = df_class_1.sample(target_count[3],replace=True)
df_class_2_under = df_class_2.sample(target_count[3],replace=True)
df_class_4_under = df_class_4.sample(target_count[3],replace=True)
df = pd.concat([df_class_1_under,df_class_2_under,df_class_3,df_class_4_under], axis=0)
ndf = df
target_count = df.Rating.value_counts()
target_count[3]
target_count.plot(kind='bar', title='Count (target)')
print("DF ISNULL: ",df.isnull().sum())

df.dtypes
#df = df.drop('y', axis=1)
#ndf = ndf.drop('y', axis=1)
df = df.sort_values(by=['Rating'], inplace=False)
#print(df)
df.columns
df = df.reset_index(drop=True)
#print(df)

ndf = ndf.sort_values(by=['Rating'], inplace=False)
#print(df)

ndf = ndf.reset_index(drop=True)
#print(df)
df.describe()


df = df.apply(pd.to_numeric,errors='coerce')
df.columns
df = df.astype('float32')
df.describe()
df.dtypes


#BOX Ploting and data procesing......

ind=df.index.to_series().groupby(df['Rating']).agg(['first','last']).reset_index()
ind
f=0
p=0
df.dtypes
df.describe()
#detecting and replacing outliers by mean
for m in range(1,4):
 A = df.loc[df['Rating'] == m]
 #print(A.shape)
 first=ind.iloc[p,1]
 #print(first)
 last=ind.iloc[p,2]
 #print(last)
 for i in range(0,27):
  #print("For i=i.value")
  Avg= np.mean(A.iloc[:,i])
  #print(Avg)
  Q1 = A.iloc[:,i].quantile(0.25)
  #print(Q1)
  Q3 = A.iloc[:,i].quantile(0.75)
  #print(Q3)
  IQR = Q3 - Q1
  lim1=(Q1 - 1.5 * IQR)
  #print(lim1)
  lim2=(Q3 + 1.5 * IQR)
  #print(lim2)
  #print(IQR)
  for ami in range(first,last+1):
      com=df.iloc[ami,i]
      if ((com < lim1) |(com > lim2)):
          #print(newdf.iloc[ami,i])
          df.iloc[ami,i] = Avg
          #print(Avg)
          #print(newdf.iloc[ami,i])
          f=f+1
  #C= A.replace(((A.iloc[ami,i] < (Q1 - 1.5 * IQR)) |(A.iloc[:,i] > (Q3 + 1.5 * IQR))), Avg)
  #print(f)
 if(p<4):
     p=p+1
     
#data without outliers boxplot
df.describe()

count=0
ndf.iloc[31:212,:1].max()


df.columns
#df = df.drop('id', axis=1)
#ndf = ndf.drop('id', axis=1)
plt.figure(figsize=(25,10))
cor = df.corr()
sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
plt.show()

#Correlation with output variable
cor_target = abs(cor["Rating"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.5]
relevant_features

df = df.iloc[:,[3,4,5,10,24,28]]

df.dtypes
y = df['Rating'].values

df = df.drop('Rating', axis=1)
df.describe()
df.dtypes
cnames = list(df.columns)
cnames
df.describe()
df.dtypes
df.isnull().sum()
df.dtypes
df = df.fillna(df.mean(), inplace=False)
df.dtypes
df.isnull().sum()
df.dtypes
df = df.astype('float32')
df.dtypes
df.describe()

#Feature selection using RS & Final Classification.
X = minmax_scaling(df,columns = cnames,min_val=0,max_val=1)
Trainaccuracy = []

Testaccuracy = []

tree = []

alldepth = []
n = 5
for i in range(n):
    print("Cross Validation: " ,i+1)
    X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.30)
    
    from scipy.stats import randint as sp_randint
    from sklearn.model_selection import RandomizedSearchCV
    
    param_grid = {'n_estimators': sp_randint(1,100),'max_depth': sp_randint(1,100)}
    classifier = RandomForestClassifier(criterion = "entropy") 
    rsearch = RandomizedSearchCV(estimator=classifier, param_distributions=param_grid, n_iter=100,scoring='accuracy',random_state=5)
    rsearch.fit(X_train, y_train)
    print(rsearch)
    # summarize the results of the random parameter search
    print(rsearch.best_score_)
    print(rsearch.best_estimator_.n_estimators,rsearch.best_estimator_.max_depth)
    tree.append(rsearch.best_estimator_.n_estimators)
    alldepth.append(rsearch.best_estimator_.max_depth)
    tree.append(rsearch.best_estimator_.n_estimators)
    alldepth.append(rsearch.best_estimator_.max_depth)
    classifier = RandomForestClassifier(criterion = "entropy",n_estimators=rsearch.best_estimator_.n_estimators,max_depth=rsearch.best_estimator_.max_depth)
    classifier.fit(X_train,y_train)
    
    P = classifier.predict(X_train)
    trainacc = float((y_train== P).sum()) / P.shape[0]
    #print('Train set accuracy: %.2f %%' % (acc*100))
    
    
    Trainaccuracy.append(trainacc)
    P = classifier.predict(X_test)
    testacc = float((y_test== P).sum()) / P.shape[0]
    #print('Test set accuracy: %.2f %%' % (acc*100))
    Testaccuracy.append(testacc)
print("\n\n")
for i in range(5): 
    print( Trainaccuracy[i]*100,"%", Testaccuracy[i]*100,"%" )
print("\n\n")
print(sum(Testaccuracy)/len(Testaccuracy))
print(sum(Trainaccuracy)/len(Trainaccuracy))